# Generated by Django 5.1.3 on 2025-03-29 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('resident', 'Resident'), ('ra', 'Resident Assistant'), ('superuser', 'Superuser')], default='resident', max_length=20),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('capacity', models.IntegerField(default=1)),
                ('occupants', models.ManyToManyField(blank=True, related_name='assigned_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
